using Microsoft.EntityFrameworkCore;
using PetApp.Models;

namespace PetApp.Data
{
    public class PetAppContext : DbContext
    {
        public PetAppContext(DbContextOptions<PetAppContext> options) : base(options)
        {
        }

        public DbSet<Pet> Pet { get; set; } = null!;
        public DbSet<User> User { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            //pet
            modelBuilder.Entity<Pet>(entity =>
            {
                // Explicitly configure primary key
                entity.HasKey(e => e.Id);

                // Ensure Id is generated by the database on add (identity)
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                // Optional: enforce simple column constraints
                entity.Property(e => e.Name).IsRequired().HasMaxLength(200);
                entity.Property(e => e.Breed).HasMaxLength(200);
            });

            //user
            modelBuilder.Entity<User>(entity =>
            {
                // Explicitly configure primary key
                entity.HasKey(e => e.Id);

                // Ensure Id is generated by the database on add (identity)
                entity.Property(e => e.Id).ValueGeneratedOnAdd();

                // Optional: enforce simple column constraints
                entity.Property(e => e.Username).IsRequired().HasMaxLength(50);
                entity.Property(e => e.Password).HasMaxLength(50);
            });
        }
    }
}
